name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run:  make
      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        run: make package
      - name: Grade
        if: startsWith(github.ref, 'refs/tags/')
        run: make grade
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ github.event.head_commit.message }}
          files: |
            nyuenc-yx2412.tar.xz
            nyuenc